### PR TITLE
[WIP] add number type usage from yargs-parser PR #7

### PR DESCRIPTION
**Pull request by lrlna**
(third time is a charm :nail_care:)

This PR requires the following before merging: 
- [x] edit usage tests
- [x] merge [new number type](https://github.com/yargs/yargs-parser/pull/7) PR
- [x] update yargs-parser version in [4.x branch](https://github.com/bcoe/yargs/tree/4.x)
- [x] update docs
- [ ] update changelog in #377

### CODE REVIEW

**Comment by bcoe** [comment]
@lrlna I've published the new parser to npm:

```
+ yargs-parser@2.1.0
```

**Comment by lrlna** [comment]
#384 is the one too look at.

**Comment by nexdrew** [comment]
@lrlna Is it safe to delete the associated branch (`add-number-type-usage`)?

**Comment by lrlna** [comment]
@nexdrew, it's completely safe. I'll do it :smile:

**Comment by nexdrew** [comment]
@lrlna Thanks!

**Pull request closed without merging**
