### PR TITLE
Locale French

### PR DESCRIPTION
**Pull request by LoicMahieu**
**`yargs` go international !**

Related to #214 

Added french language. **Still work in progress**. I would like some review from other french speaking people. I'll ask my colleagues but it'll be most better if community can review it too.

Is it a good idea to translate types ? 
I wasn't confortable to translate this kind of words, closely linked with programming and computer science. In current review, it is not translated.

### CODE REVIEW

**Comment by nexdrew** [comment]
Awesome, thanks @LoicMahieu!

I would say the types could go either way - whatever is most familiar to French-speaking peoples. At least `count` could probably be translated, no?

**Comment by bcoe** [comment]
@LoicMahieu I'm really happy with this, do you think it's ready to merge? we can allow others to edit after the fact.

**Comment by LoicMahieu** [comment]
Review done! There were some mistakes, thankfully corrected. Types are finally translated, people I asked were comfortable with the translation.
Ready to merge!

**Comment by bcoe** [comment]
Awesome thank you @LoicMahieu!

**Comment by bcoe** [comment]
@LoicMahieu `fr` is released in `yargs@3.17.1`, thanks!

**Pull request merged**
