### PR TITLE
Find the config file in the nearest parent folder

### PR DESCRIPTION
**Pull request by cbas**
Travels up the folder hierarchy until a configuration file is found.
Same behaviour as npm, babel, jscs, jshint, etc.

### CODE REVIEW

**Comment by cbas** [comment]
Hmm what gives with AppVeyor? Runs fine on Travis. Is this a known issue?

**Comment by cbas** [comment]
Q: Should this behaviour be opt-in to remain backwards compatible? Could add an argument like `.config(key, [description], [bubble])` for example where `bubble` is a Boolean and defaults to false.

**Comment by bcoe** [comment]
The AppVeyor tests are definitely passing, so this appears to be surfacing a legitimate difference between the tests on Linux vs. the tests on Windows.

I appreciate the pull request, but I'm not quite sure that I'd like to add this behavior. By convention, it's common to have a `.foorc` crawl the directory structure until it hits a matching file -- for a JSON configuration file I think this behavior is not expected.

When I'm deploying to production I might have a `config.json` in the project directory, it would be unexpected behavior to have the application pluck a `config.json` from a few levels up the directory hierarchy. Does anyone else want to chime in on this, @nexdrew? just my gut feeling.

**Comment by nexdrew** [comment]
I've been giving this some thought, and I'm not quite sure. It might make sense if you want to *always* use a config file, and specify a default file name to look for, so that CLI users don't have to specify a config option at all (unless overriding the default), but I'm not sure it makes sense when a config argument is explicitly given by the CLI user.

I tend to agree with @bcoe on this but could be persuaded otherwise. If we *do* add the functionality, I would prefer it to be opt-in instead of enabled by default.

@cbas Could you possibly run through a couple use-cases for us?

**Comment by cbas** [comment]
@bcoe @nexdrew I appreciate the consideration and feedback, thank you.

1. I will need to take a look at the Windows issue. I thought it was odd to be failing in a test following the one I added, as that should be unrelated. Maybe the tweak to `cwd` somehow broke things (just a guess). :worried:

1. The use case is based on an observation that several popular tools currently use JSON-formatted config files combined with the directory-traversing lookup behaviour. The files are still called `rc`-files but contain, in fact, JSON. Examples of tools with directory traversing lookup behaviour would be:
  - `npm` with `package.json`
    e.g. `npm test` works the same from any child directory
  - `babel` with `.babelrc` (actually JSON)
  - `jscs` with `.jscs` (actually JSON)
  - `jschint` with `.jshintrc` (actually JSON)

**Comment by nexdrew** [comment]
Don't mean to be blunt, but why not use something like [rc](https://www.npmjs.com/package/rc) instead? Just convenience?

**Comment by cbas** [comment]
:flushed: TIL :sob:

**Comment by nexdrew** [comment]
@cbas No worries! It's not a bad idea, but I would rather offer a more robust solution, and I think other modules might fit that bill better than yargs. Just my 2¢. :wink:

**Comment by cbas** [comment]
Thanks again for the feedback. Building this was a nice learning project. It gave me a much better understanding of yargs. Hope to contribute something suitable in the future! :+1:

**Comment by bcoe** [comment]
@cbas was about to say, I hope this doesn't discourage you from contributing \o/ One thing worth discussing in the future, is does `yargs@4.x` itself just use `rc`?

**Comment by nexdrew** [comment]
Definitely worth consideration, I think. Props to @cbas for bringing this up!

**Pull request closed without merging**
