### PR TITLE
added contributor code of conduct, and contribution guidelines

### PR DESCRIPTION
**Pull request by bcoe**
* added a contributor code of conduct, care of http://contributor-covenant.org/
* added a brief list of instructions to help folks get started with contributions.

### CODE REVIEW

**Comment by bcoe** [comment]
@nexdrew @lrlna @maxrimue how do folks feel about these contribution guidelines?

**Comment by maxrimue** [comment]
Looks very good :+1:

**Comment by nexdrew** [comment]
LGTM :+1: 

I was thinking it might be useful to have a test that checks for an email address in the doc, but it probably won't change and might be overkill.

I don't wanna get too crazy here, but do you think it makes sense to create an email address we can use as a distribution list for all interested project maintainers? There are at least 2 places now that we could use this (and it might come in handy for other places too):
- The yargs org in GitHub
- The code of conduct

Anyway, just a thought. It need not block this pull. I vote :shipit:

**Comment by lrlna** [comment]
:+1: for code of conduct part
:+1: for contributing guidelines

I am thinking though, would it be useful to have something explaining how to contribute? Or most of the contributors know what they are doing? My most fahttps://github.com/npm/docs/blob/master/CONTRIBUTING.md#contributvourite example is the little [to-do list](https://github.com/npm/docs/blob/master/CONTRIBUTING.md#contributing) on npm docs. The first couple of times I've had to contribute anywhere I basically looked back at it. But again, might not be useful for our contributors. 

Also like [johnny-five](https://github.com/rwaldron/johnny-five/blob/master/CONTRIBUTING.md) guidelines a lot; they walk you through submitting an issue, testing etc :tada: 

I, however, don't want to block this. I think we can totally merge this, and then improve it if we so wish to ^.^

**Comment by bcoe** [comment]
@nexdrew I agree, we should create a separate email at some point -- I'm going to use my personal email for the time being so that we can land this and cut a release, but I'll look into setting up a free Google Organization.

**Comment by lrlna** [comment]
YAY! `contributing.md` is a thing! :confetti_ball: :leaves: Thanks @bcoe !

**Pull request merged**
