### PR TITLE
Reinstate os-locale with option to prohibit spawning

### PR DESCRIPTION
**Pull request by nexdrew**
`os-locale@1.3.1` allows us to nuke the previous stop-gap solution. Now we can tell `os-locale` not to spawn any subprocesses, so we don't introduce unnecessary latency or, even worse, problems with installing `spawn-sync`, for downstream dependents like Atom. :sunglasses:

If the build fails due to `standard` problems, anything not handled by PR #247 will be subsequently fixed here.

### CODE REVIEW

**Comment by nexdrew** [comment]
@bcoe When you get a chance, this PR needs review. Thanks!

**Comment by bcoe** [comment]
awesome \o/ will make the time this evening.

**Comment by bcoe** [comment]
Great work :sunglasses:, :shipit:

**Comment by nexdrew** [comment]
Published as `yargs@3.24.0`

**Pull request merged**
