### PR TITLE
Added the locale pt-BR (Portuguese Brazil).

### PR DESCRIPTION
**Pull request by JulioGold**
Just added the locale pt-BR (Portuguese Brazil).

Obrigado

### CODE REVIEW

**Comment by nexdrew** [comment]
@JulioGold :cool: Awesome, thanks! I'll get this merged in soon.

**Comment by bcoe** [comment]
\o/ I'm in Rio for my honeymoon, this contribution came at the perfect time. Thanks for the contribution @JulioGold, @nexdrew merge at will.

**Comment by nexdrew** [comment]
Merged. :tada: :fireworks: Thanks again, @JulioGold!

Note that I took the liberty of making sure indentation of the new JSON file matched that of the other locale files, and I changed the locale description in the README from "Portuguese Brazil" to "Brazilian Portuguese" for consistency with others (e.g. "American English").

Side note: I fetched the PR branch to add a commit and then merged to master locally (with fast-forward), so I ended up with a "clean" commit history, but there isn't a commit message that references the PR number. :disappointed: So, unfortunately, we can't tell just from the commit history that the changes came from this PR. I've been [experimenting with different PR merge methods](https://github.com/sindresorhus/ama/issues/256) recently, and I'm not quite sure which method is best, but I'll try to do this better next time.

**Comment by JulioGold** [comment]
I'm very grateful to contribute and I'll read the indication of PR.
@bcoe I hope you had a great honeymoon.

Thanks

**Pull request merged**
